/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeedatabase;

/**
 *
 * @author xenoc
 */
public class MainPanel extends javax.swing.JFrame {
    boolean isAdmin;

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageusersButton = new javax.swing.JToggleButton();
        accessdbButton = new javax.swing.JToggleButton();
        logoutButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(413, 230));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageusersButton.setText("Manage Users");
        manageusersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageusersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manageusersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 75, 135, -1));

        accessdbButton.setText("Access Database");
        accessdbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessdbButtonActionPerformed(evt);
            }
        });
        getContentPane().add(accessdbButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 110, 135, -1));

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 145, 135, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Control Panel");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 10, 155, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginForm loginForm = new LoginForm();
        loginForm.setLocationRelativeTo(null);
        loginForm.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void manageusersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageusersButtonActionPerformed
        ManageUserForm manageUserForm = new ManageUserForm();
        manageUserForm.setLocationRelativeTo(null);
        manageUserForm.setVisible(true);
        manageUserForm.isAdmin = isAdmin;
        
        this.dispose();
    }//GEN-LAST:event_manageusersButtonActionPerformed

    private void accessdbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessdbButtonActionPerformed
        DatabasePanel databasePanel = new DatabasePanel();
        databasePanel.setLocationRelativeTo(null);
        databasePanel.setVisible(true);
        databasePanel.isAdmin = isAdmin;
        
        this.dispose();
    }//GEN-LAST:event_accessdbButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton accessdbButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton logoutButton;
    public javax.swing.JToggleButton manageusersButton;
    // End of variables declaration//GEN-END:variables
}
