/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeedatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author xenoc
 */
public class RegisterForm extends javax.swing.JFrame {
    boolean isAdmin;

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        adminField = new javax.swing.JCheckBox();
        registerButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        titlePanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(413, 290));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 69, 170, -1));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 101, 170, -1));
        getContentPane().add(adminField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 87, -1));

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 170, 135, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 205, 135, -1));

        titlePanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titlePanel.setText("Register User");
        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 25, 150, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 66, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Is Admin:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 98, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        ManageUserForm manageUserForm = new ManageUserForm();
        manageUserForm.setLocationRelativeTo(null);
        manageUserForm.setVisible(true);
        manageUserForm.isAdmin = isAdmin;
        
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String username = usernameField.getText();
        username = username.trim();
        
        char[] password = passwordField.getPassword();
        password = new String(password).trim().toCharArray();
        
        Boolean isAdmin = adminField.isSelected();
        
        if (username.length() == 0 || password.length == 0) {
            JOptionPane.showMessageDialog(null, "That is not a valid username or password!", "User Creation Failure", JOptionPane.WARNING_MESSAGE);
        
            return;
        }
        
        Connection conn = null;
        
        try {            
            conn = DriverManager.getConnection(DBCredentials.CONN_STRING, DBCredentials.USERNAME, DBCredentials.PASSWORD);
            Statement stmt = conn.createStatement();
            
            String st = "SELECT access_accounts.username username FROM access_accounts WHERE ";
            st = st + "username = \"" + username + "\"";
                       
            ResultSet rs = stmt.executeQuery(st);
            Boolean exists = false;

            if (rs.next()) {
                exists = true;
            }
                        
            conn.close();
            
            if (exists) {
                JOptionPane.showMessageDialog(null, "A user with that name already exists!", "User Duplicate", JOptionPane.ERROR_MESSAGE);
            
                return;
            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        conn = null;
        
        try {            
            conn = DriverManager.getConnection(DBCredentials.CONN_STRING, DBCredentials.USERNAME, DBCredentials.PASSWORD);
            Statement stmt = conn.createStatement();
            
            String st = "INSERT INTO `access_accounts` (`id`, `username`, `password`, `isAdmin`) VALUES (NULL, '";
            st = st + username + "', '";
            st = st + new String(password) + "', '";
            
            if (isAdmin) {
                st = st + "1')";
            } else {
                st = st + "0')";
            }
            
            stmt.executeUpdate(st);
                        
            conn.close();
            
            String userType = "User";
            if (isAdmin) userType = "Admin";
            
            JOptionPane.showMessageDialog(null, userType + " '" + username + "' registered!", "User Created", JOptionPane.INFORMATION_MESSAGE);
        
            ManageUserForm manageUserForm = new ManageUserForm();
            manageUserForm.setLocationRelativeTo(null);
            manageUserForm.setVisible(true);
            manageUserForm.isAdmin = this.isAdmin;

            this.dispose();
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel titlePanel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
