/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeedatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author xenoc
 */
public class RegisterEmployeeForm extends javax.swing.JFrame {
    boolean isAdmin;

    /**
     * Creates new form RegisterEmployeeForm
     */
    public RegisterEmployeeForm() {
        initComponents();
    }
    
    private float verifyFloat(String fieldName, String strNumber) {
        float number;
        
        try {
            number = Float.valueOf(strNumber);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, fieldName + " is not valid!", "Invalid " + fieldName, JOptionPane.WARNING_MESSAGE);
        
            number = -1;
        }
        
        return number;
    }
    
    private int verifyInt(String fieldName, String strNumber) {
        int number;
        
        try {
            number = Integer.parseInt(strNumber);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, fieldName + " is not valid!", "Invalid " + fieldName, JOptionPane.WARNING_MESSAGE);
        
            number = -1;
        }
        
        return number;
    }
    
    private String verifyField(String fieldName, String field) {
        if (field.length() < 1) {
            JOptionPane.showMessageDialog(null, fieldName + " is not valid!", "Invalid " + fieldName, JOptionPane.WARNING_MESSAGE);
        
            return "";
        }
        
        return field;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        surnameField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        titlePanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fathersnameField = new javax.swing.JTextField();
        mothersnameField = new javax.swing.JTextField();
        tinField = new javax.swing.JTextField();
        ssnField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        email1Field = new javax.swing.JTextField();
        email2Field = new javax.swing.JTextField();
        employeetypeField = new javax.swing.JTextField();
        vacanciesField = new javax.swing.JTextField();
        workhoursField = new javax.swing.JTextField();
        salarytypeField = new javax.swing.JTextField();
        kidcountField = new javax.swing.JTextField();
        maritalstatusField = new javax.swing.JTextField();
        educationlevelField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(413, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(surnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 101, 170, -1));

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 600, 135, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 635, 135, -1));

        titlePanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titlePanel.setText("Register Employee");
        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 25, 210, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Education Level:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 549, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Surname:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 98, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Father's Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mother's Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 162, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("TIN:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 194, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("SSN:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 226, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Address:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 258, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Email 1:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Email 2:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 322, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Employee Type:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 354, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Vacancies:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 386, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Work Hours:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 418, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Salary Type:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 450, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Kid Count:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 483, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Marital Status:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 516, -1, -1));
        getContentPane().add(fathersnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 133, 170, -1));
        getContentPane().add(mothersnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 165, 170, -1));
        getContentPane().add(tinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 197, 170, -1));
        getContentPane().add(ssnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 229, 170, -1));
        getContentPane().add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 261, 170, -1));
        getContentPane().add(email1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 293, 170, -1));
        getContentPane().add(email2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 325, 170, -1));
        getContentPane().add(employeetypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 357, 170, -1));
        getContentPane().add(vacanciesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 389, 170, -1));
        getContentPane().add(workhoursField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 421, 170, -1));
        getContentPane().add(salarytypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 453, 170, -1));
        getContentPane().add(kidcountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 485, 170, -1));
        getContentPane().add(maritalstatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 518, 170, -1));
        getContentPane().add(educationlevelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 551, 170, -1));
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 69, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String name = nameField.getText().trim();
        name = verifyField("Name", name);
        if (name.equals("")) return;
        
        String surname = surnameField.getText().trim();
        surname = verifyField("Surname", surname);
        if (surname.equals("")) return;
        
        String fathersname = fathersnameField.getText().trim();
        fathersname = verifyField("Father's Name", fathersname);
        if (fathersname.equals("")) return;
        
        String mothersname = mothersnameField.getText().trim();
        mothersname = verifyField("Mother's Name", mothersname);
        if (mothersname.equals("")) return;
        
        String strTin = tinField.getText().trim();
        strTin = verifyField("TIN", strTin);
        if (strTin.equals("")) return;
        int tin = verifyInt("TIN", strTin);
        if (tin == -1) return;
        
        String strSsn = ssnField.getText().trim();
        strSsn = verifyField("SSN", strSsn);
        if (strSsn.equals("")) return;
        int ssn = verifyInt("SSN", strSsn);
        if (ssn == -1) return;
        
        String address = addressField.getText().trim();
        address = verifyField("Address", address);
        if (address.equals("")) return;
        
        String email1 = email1Field.getText().trim();
        email1 = verifyField("Email 1", email1);
        if (email1.equals("")) return;
        
        String email2 = email2Field.getText().trim();
        email2 = verifyField("Email 2", email2);
        if (email2.equals("")) return;
        
        String employeetype = employeetypeField.getText().trim();
        employeetype = verifyField("Employee Type", employeetype);
        if (employeetype.equals("")) return;
        
        String strVacancies = vacanciesField.getText().trim();
        strVacancies = verifyField("Vacancies", strVacancies);
        if (strVacancies.equals("")) return;
        int vacancies = verifyInt("Vacancies", strVacancies);
        if (vacancies == -1) return;
        
        String strWorkhours = workhoursField.getText().trim();
        strWorkhours = verifyField("Work Hours", strWorkhours);
        if (strWorkhours.equals("")) return;
        float workhours = verifyFloat("Work Hours", strWorkhours);
        if (workhours == -1) return;
        
        String salarytype = salarytypeField.getText().trim();
        salarytype = verifyField("Salary Type", salarytype);
        if (salarytype.equals("")) return;
        
        String strKidcount = kidcountField.getText().trim();
        strKidcount = verifyField("Kid Count", strKidcount);
        if (strKidcount.equals("")) return;
        int kidcount = verifyInt("Kid Count", strKidcount);
        if (kidcount == -1) return;
        
        String maritalstatus = maritalstatusField.getText().trim();
        maritalstatus = verifyField("Marital Status", maritalstatus);
        if (maritalstatus.equals("")) return;
        
        String educationlevel = educationlevelField.getText().trim();
        educationlevel = verifyField("Education Level", educationlevel);
        if (educationlevel.equals("")) return;
                
        Connection conn = null;
        
        try {            
            conn = DriverManager.getConnection(DBCredentials.CONN_STRING, DBCredentials.USERNAME, DBCredentials.PASSWORD);
            Statement stmt = conn.createStatement();
            
            String st = "INSERT INTO `employees` (`id`, `name`, `surname`, `father_name`, `mother_name`, `TIN`, `SSN`, `address`, `email_1`, `email_2`, `employee_type`, `vacancies`, `work_hours`, `salary_type`, `kid_count`, `marital_status`, `education_level`) VALUES (NULL, '";
            st = st + name + "', '";
            st = st + surname + "', '";
            st = st + fathersname + "', '";
            st = st + mothersname + "', '";
            st = st + tin + "', '";
            st = st + ssn + "', '";
            st = st + address + "', '";
            st = st + email1 + "', '";
            st = st + email2 + "', '";
            st = st + employeetype + "', '";
            st = st + vacancies + "', '";
            st = st + workhours + "', '";
            st = st + salarytype + "', '";
            st = st + kidcount + "', '";
            st = st + maritalstatus + "', '";
            st = st + educationlevel + "')";
            
            stmt.executeUpdate(st);
                        
            conn.close();
            
            JOptionPane.showMessageDialog(null, "Employee registered!", "Employee Registered", JOptionPane.INFORMATION_MESSAGE);
        
            DatabasePanel databasePanel = new DatabasePanel();
            databasePanel.setLocationRelativeTo(null);
            databasePanel.setVisible(true);
            databasePanel.isAdmin = isAdmin;
        
            this.dispose();
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        DatabasePanel databasePanel = new DatabasePanel();
        databasePanel.setLocationRelativeTo(null);
        databasePanel.setVisible(true);
        databasePanel.isAdmin = isAdmin;

        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterEmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField educationlevelField;
    private javax.swing.JTextField email1Field;
    private javax.swing.JTextField email2Field;
    private javax.swing.JTextField employeetypeField;
    private javax.swing.JTextField fathersnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kidcountField;
    private javax.swing.JTextField maritalstatusField;
    private javax.swing.JTextField mothersnameField;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField salarytypeField;
    private javax.swing.JTextField ssnField;
    private javax.swing.JTextField surnameField;
    private javax.swing.JTextField tinField;
    private javax.swing.JLabel titlePanel;
    private javax.swing.JTextField vacanciesField;
    private javax.swing.JTextField workhoursField;
    // End of variables declaration//GEN-END:variables
}
